install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-science
    - sudo apt-get install chktex
 
script:
    - cd LaTeX
    - chktex -W # Print version information.
    - chktex -q -n 6 *.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    - test ! -s lint.out
    - pdflatex *.tex
    - pdflatex *.tex
